version: '3.8'

services:
  # サービス名を "web" とします
  web:
    # 同じディレクトリにあるDockerfileを使ってイメージをビルドします
    build:
      context: .
    # コンテナのポート3000を、ホストマシン（PC）のポート3000に接続します
    ports:
      - "3000:3000"
    # ホストマシンのカレントディレクトリをコンテナの/appに同期させます
    # これにより、コードを編集すると即座に開発サーバーに反映されます
    volumes:
      - .:/app
      # node_modulesはホストマシンと同期させないように設定します（パフォーマンス向上のため）
      - /app/node_modules
    # .env.localファイルに書かれた環境変数をコンテナに読み込ませます
    env_file:
      - .env.local